// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdcfpwfxnxbxkzqaztdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkY2Zwd2Z4bnhieGt6cWF6dGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTA2ODAsImV4cCI6MjA2NzcyNjY4MH0.dsCGFNSjpLf1oBO8Lywde9gvGqtY3KZ0IjfkCigzje8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});